### ISSUE TITLE
Using AffectToolbox with Pre-Recorded Video and Audio

### ISSUE THREAD

**Issue by Mikinox3** [hcmlab/AffectToolbox#5]
Hi! I’m trying to use AffectToolbox to extract emotion dimensions from pre-recorded video and audio files, rather than using real-time streams from the camera and microphone.

For the video input, I found a workaround by modifying line 247 in AffectPipeline.py:

self.capture = cv2.VideoCapture(self.cam_options["cam_id"])

to:

self.capture = cv2.VideoCapture($VIDEOPATH)

This seems to resolve the issue for video, but I’m having trouble doing the same for audio inputs.

I’ve already modified lines 233-241 in AffectPipeline.py to adapt the parameters for my audio input and also updated the microphone_loop_func(self). However, these changes don’t seem to be enough, and I’m not sure what else needs to be modified to make it work.

Any guidance on how to properly handle pre-recorded audio with AffectToolbox would be much appreciated!

**Comment by SilvanMertes** [comment]
Hi! So at the moment we are using pyaudio for the audio input stream. pyaudio does not have the option to use a file as input stream, however there is a little workaround that might help. You could use the "wave" library to load the file and "simulate" a microphone stream. So something like this could do the trick: 

```
import wave

def open_stream(self):
        self.p_audio = pyaudio.PyAudio()
        self.file_source = wave.open('input.wav', 'rb')
        s_width = self.file_source.getsampwidth()
        format = self.p_audio.get_format_from_width(s_width)
        channels = self.file_source.getnchannels()
        rate = self.file_source.getframerate()
        self.stream = self.p_audio.open(format=format,
                                        channels=channels,
                                        rate=rate,
                                        frames_per_buffer=1024,
                                        input=False,
                                        output=True,
                                        output_device_index=detect_build_in_output_device_idx(self.p_audio),
                                        stream_callback=self.__recording_callback)


def __recording_callback(self, in_data, frame_count, time_info, status):

        # read frames
        in_data = self.file_source.readframes(frame_count)
        # decode frames
        left, right = audio_decode(in_data, self.file_source.getnchannels())
        # process frames
        left, right = self.core.process(left, right)
        # encode back
        processed_data = audio_encode((left, right))

        return processed_data, pyaudio.paContinue
```

I found that code snippet on stackoverflow and did not yet try if it works with the AffectToolbox. So you would have to adapt it accordingly, put it in the right places etc.
Thanks for using the AffectToolbox! If you manage do get it running with local pre-recorded files, please also make a pull request here, I would be glad to include it into the repository!
All the best,
Silvan

**Comment by Mikinox3** [comment]
@SilvanMertes  Thank you for your answer, here are the changes I made to make it working :

In AffectPipeline.py :

wav_file = '/path_to_test.wav'
wf = wave.open(wav_file, 'rb')
self.SAMPLE_RATE=wf.getframerate()
self.CHANNELS = wf.getnchannels()
 #self.CHUNK_SIZE = int(self.STEP * self.SAMPLE_RATE)
 self.CHUNK_SIZE=1024

if self.VAD_LOOP or self.SER_LOOP or self.STT_LOOP:
            
            self.audio = pyaudio.PyAudio()
            self.stream = self.audio.open(
                                          format=self.audio.get_format_from_width(wf.getsampwidth()),
                                          channels=self.CHANNELS,
                                          rate=self.SAMPLE_RATE,
                                          output=True,
                                          input = False,
                                          frames_per_buffer=self.CHUNK_SIZE)

    def microphone_loop_func(self):
    
        while not self.stop_thread:
            data = wf.readframes(self.CHUNK_SIZE)
            while data:
                self.stream.write(data)
                data = wf.readframes(self.CHUNK_SIZE)
                signal = np.frombuffer(data, dtype=np.int16)
                signal_list = signal.tolist()

                for n in range(0, len(signal_list)):
                    qs.AUDIO_QUEUE.append(signal_list[n])
        print("Thread ended")

It works well for SER and VAD, but the STT seems less efficient compared to the microphone input speech. The code should be updated so that the user can choose between processing a recording or streaming voice in real-time.

Best

Mathilde
